sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

matrix:
  include:
    - python: 3.5
      env:
      - TOXENV=flake8

install:
  - pip install coveralls
  - pip install tox-travis

script:
  - tox

after_success:
  - coveralls
