language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 .
  - ./test_spec.py
  - coverage run --source=chevron ./test_spec.py
after_success:
  - coveralls
